server:
  port: 8080

spring:
  application:
    name: jdk17app
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  h2: #H2 Web 控制台配置，启用 h2 Console 控制台，并设置访问路径
    console:
      enabled: true
      path: /h2_console
  datasource: #多数据源配置
    dynamic:
      enabled: true #启用动态数据源，默认为true
      primary: master #设置默认的数据源或者数据源组,默认为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      grace-destroy: false #是否优雅关闭数据源，默认为false，设置为true时，关闭数据源时如果数据源中还存在活跃连接，至多等待10s后强制关闭
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
        element:
          url: jdbc:mysql://127.0.0.1:3306/mysql?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
        workflow:
          url: jdbc:mysql://127.0.0.1:3306/sys?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
        h2_frame:
          #AUTO_SERVER=TRUE 表示使用混合模式，此时可以支持多个连接。默认情况下，H2 只运行一个进程访问.
          #"~" 表示系统当前登录用户的根目录。test数据库不存在时会自动创建;
          url: jdbc:h2:~/test_frame;AUTO_SERVER=TRUE
          username: admin #数据库不存在时，h2 会自动新建，此时账号密码自定义即可
          password: 123456
          driver-class-name: org.h2.Driver
        sqlite_pm:
          # 指定sqlite数据库文件地址,一个文件相当于一个数据库,目录必须存在,文件不存在时会自动新建;SQLite可以不需要配置账号与密码;
          # ${user.home} 表示用户的根目录，如 C:\Users\用户名
          url: jdbc:sqlite:${user.home}\test_pm.db
          driver-class-name: org.sqlite.JDBC